name: 'Deploy on master merge'

on:
  pull_request:
    branches: [ master ]
    types: [closed]

    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    outputs:
      boards: ${{ steps.list-boards.outputs.boards }}
    steps:
      - uses: actions/checkout@v3

      - name: 'Fetch latest tag'
        id: get-latest-tag
        uses: "actions-ecosystem/action-get-latest-tag@v1"
        if: ${{ steps.release-label.outputs.level != null }}

      - name: 'Fetch all boards'
        id: list-boards
        run: |
          echo "::set-output name=boards::$(find -maxdepth 1 -name \"*coffee\" -exec basename {} \; | cut -d '.' -f1)"

  deploy:
    needs: fetch
    runs-on: ubuntu-latest
    strategy:
      matrix:
        board: ${{  jobs.fetch.list-boards.outputs.boards }}
    steps:
      - name: Triggers a deploy job
        run: |
          echo "Deploying" ${{ matrix.board }}
