name: 'Deploy on release tag'

on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+\+?r?e?v?[0-9]?
      - v20[0-9][0-9].[0-1]?[1470].[0-9]+

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release-on-tag:
    uses: balena-os/github-workflows/.github/workflows/build_and_deploy.yml@11ed17ed7e3944ad3ec2c1510fea4d30121f2e47
    with:
      deployTo: "staging"
      final: "no"
    secrets: inherit
